# Generated by Django 5.0.2 on 2024-07-28 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0006_alter_user_username"),
        ("authentication", "0011_alter_passwordresettoken_expires_at"),
    ]

    operations = []
