version: "3"

services:
  postgres:
    image: "postgres:latest"
    # restart: "always"
    environment:
      - POSTGRES_DB=${PG_NAME}
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data

  django:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "0.0.0.0:8000:8000"
    env_file:
      - ./.env
    environment:
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DB_NAME=${PG_NAME}
      - DB_USER=${PG_USER}
      - DB_PASSWORD=${PG_PASSWORD}
      - DB_HOST=${PG_HOST}
      - DB_PORT=${PG_PORT}
    depends_on:
      - postgres
    # restart: "always"
    command: ["bash",
              "-c",
              "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"]

  react:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "0.0.0.0:3000:3000"
    env_file:
      - ./client/.env
    depends_on:
      - django
    command: ["bash",
              "-c",
              "npm install && npm start"]

volumes:
  postgres-data:
  localstack-data: