# Generated by Django 5.0.2 on 2024-05-25 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dashboard",
            name="image_url",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
