# Generated by Django 5.0.2 on 2024-05-27 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_dashboard_image_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dashboard",
            name="image_url",
        ),
        migrations.AddField(
            model_name="dashboard",
            name="image",
            field=models.URLField(blank=True, null=True),
        ),
    ]
