# Generated by Django 5.0.2 on 2024-06-08 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0004_dashboard_created_at_dashboard_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dashboard",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
