# Generated by Django 5.0.2 on 2024-06-10 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0006_alter_dashboard_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dashboard",
            old_name="verified",
            new_name="is_verified",
        ),
    ]
