# Generated by Django 5.0.2 on 2024-06-23 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0007_rename_verified_dashboard_is_verified"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dashboard",
            name="is_verified",
        ),
    ]
