# Generated by Django 5.0.2 on 2024-08-05 06:02

import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=products.models.product_image_upload_to
            ),
        ),
    ]
