# Generated by Django 5.0.2 on 2024-08-06 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_case_cooling_cpu_graphicscard_hdd_motherboard_psu_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cooling",
            old_name="Db_max_noise_level",
            new_name="db_max_noise_level",
        ),
        migrations.AlterField(
            model_name="motherboard",
            name="processor_manufacturer",
            field=models.CharField(choices=[("Intel", "Intel"), ("AMD", "AMD")]),
        ),
        migrations.AlterField(
            model_name="product",
            name="available_in_stock",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterModelTable(
            name="cooling",
            table="cooling",
        ),
        migrations.AlterModelTable(
            name="hdd",
            table="hdd",
        ),
        migrations.AlterModelTable(
            name="psu",
            table="psu",
        ),
        migrations.AlterModelTable(
            name="ram",
            table="ram",
        ),
    ]
