# Generated by Django 5.0.2 on 2024-08-06 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "products",
            "0004_rename_db_max_noise_level_cooling_db_max_noise_level_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelTable(
            name="ssd",
            table="ssd",
        ),
    ]
